import Link from "next/link";
import Icon from "@/components/Icon";
import Logo from "@/components/Logo";
import PrintButton from "@/components/PrintButton";
import { currentUser } from "@/lib/session";
import { prisma } from "@/lib/prisma";

export const metadata = { title: "CV Builder" };
export const dynamic = "force-dynamic";

const pretty = (s: string) => s.split("_").map((w) => w[0] + w.slice(1).toLowerCase()).join(" ");

export default async function CvBuilder() {
  const u = await currentUser();
  const p = u?.candidate?.id
    ? await prisma.candidateProfile.findUnique({
        where: { id: u.candidate.id },
        select: { profession: true, city: true, experienceYrs: true, saudiExpYrs: true, salaryExpect: true, education: true, skills: true, languages: true, drivingLicense: true, summary: true, certifications: true, user: { select: { email: true, phone: true } }, documents: { where: { status: "VERIFIED" }, select: { type: true } } },
      })
    : null;

  const verified = (p?.documents ?? []).map((d) => pretty(d.type));

  return (
    <div className="space-y-5">
      <div className="no-print flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold text-navy">CV Builder</h1>
          <p className="text-sm text-navy/60">Your professional CV, generated from your profile. Print or save as PDF.</p>
        </div>
        <div className="flex gap-2">
          <Link href="/candidate/profile" className="btn-outline no-print"><Icon name="users" className="h-4 w-4" /> Edit profile</Link>
          <PrintButton />
        </div>
      </div>

      {/* CV sheet */}
      <div className="cv-sheet mx-auto max-w-3xl rounded-2xl border border-navy/10 bg-white p-8 shadow-sm sm:p-10">
        <div className="flex items-start justify-between border-b border-navy/10 pb-5">
          <div>
            <h2 className="text-3xl font-extrabold text-navy">{u?.name ?? "Your Name"}</h2>
            <p className="mt-1 text-lg font-semibold text-brand">{p?.profession ?? "Professional"}</p>
            <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm text-navy/60">
              {p?.city && <span className="flex items-center gap-1"><Icon name="pin" className="h-4 w-4" />{p.city}</span>}
              {p?.user?.email && <span className="flex items-center gap-1"><Icon name="chat" className="h-4 w-4" />{p.user.email}</span>}
              {p?.user?.phone && <span className="flex items-center gap-1"><Icon name="chat" className="h-4 w-4" />{p.user.phone}</span>}
            </div>
          </div>
          <Logo />
        </div>

        {p?.summary && (
          <Section title="Professional Summary"><p className="text-sm leading-relaxed text-navy/75">{p.summary}</p></Section>
        )}

        <Section title="Key Details">
          <div className="grid gap-y-2 text-sm sm:grid-cols-2">
            <Detail label="Total experience" value={`${p?.experienceYrs ?? 0} years`} />
            <Detail label="Overseas experience" value={`${p?.saudiExpYrs ?? 0} years`} />
            <Detail label="Education" value={p?.education ?? "—"} />
            <Detail label="Driving license" value={p?.drivingLicense ?? "—"} />
            <Detail label="Expected salary" value={p?.salaryExpect ?? "—"} />
            <Detail label="Languages" value={(p?.languages ?? []).join(", ") || "—"} />
          </div>
        </Section>

        {(p?.skills?.length ?? 0) > 0 && (
          <Section title="Skills">
            <div className="flex flex-wrap gap-2">
              {p!.skills.map((s) => <span key={s} className="rounded-full bg-brand/10 px-3 py-1 text-xs font-medium text-brand-dark">{s}</span>)}
            </div>
          </Section>
        )}

        {(p?.certifications?.length ?? 0) > 0 && (
          <Section title="Certifications">
            <ul className="list-inside list-disc text-sm text-navy/75">{p!.certifications.map((c) => <li key={c}>{c}</li>)}</ul>
          </Section>
        )}

        {verified.length > 0 && (
          <Section title="Verified Documents">
            <div className="flex flex-wrap gap-2">
              {verified.map((d) => <span key={d} className="inline-flex items-center gap-1 rounded-full bg-brand/5 px-3 py-1 text-xs font-medium text-brand-dark"><Icon name="check-circle" className="h-3.5 w-3.5" /> {d}</span>)}
            </div>
          </Section>
        )}

        <div className="mt-8 border-t border-navy/10 pt-4 text-center text-xs text-navy/40">
          Verified candidate profile · Generated by ForcePK · forcepk.com
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-6">
      <h3 className="text-sm font-bold uppercase tracking-wider text-navy/70">{title}</h3>
      <div className="mt-2">{children}</div>
    </div>
  );
}
function Detail({ label, value }: { label: string; value: string }) {
  return <div><span className="text-navy/50">{label}: </span><span className="font-medium text-navy">{value}</span></div>;
}
